[package]
name = "jobshop-python"
version = "0.1.0"
authors = ["Mimikkk <Inwazzin@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "*"
rand = "*"
futures = "*"
async-std = { version = "*", features= ["attributes"] }
